### ISSUE TITLE
Spinning wheel on the Ballerina Diagram after Swan Lake Beta 5 upgrade

### ISSUE THREAD

**Issue by cpklein** [wso2/ballerina-plugin-vscode#140]
**Description:**

Ballerina Diagram displays an empty grid with a spinning wheel in the center

**Steps to reproduce:**
I've just gone through the recommended upgrade process from slbeta3:
bal update
bal dist pull slbeta5

I'm also no longer able to access exemple files but I'm not sure if there is any relationship:
cannot open file:///Library/Ballerina/examples/hello-world/hello_world.bal. Detail: Unable to read file '/Library/Ballerina/examples/hello-world/hello_world.bal' (Error: Unable to resolve nonexistent file '/Library/Ballerina/examples/hello-world/hello_world.bal')

**OS, DB, other environment details and versions:**
I'm running MacOS 11.6.1

**Comment by prabushi** [comment]
This could be due to an issue in the Ballerina version picked up by the VS Code extension. Please check if the Ballerina version is properly set in the extension status bar. 

<img width="311" alt="Screenshot 2022-05-12 at 15 45 05" src="https://user-images.githubusercontent.com/5234623/168048582-8614a93f-87c8-4917-b689-3acff9dd45c5.png">

@cpklein Did you encounter the mentioned issue with the latest releases?

**Comment by prabushi** [comment]
We have released Ballerina extension 3.0.1. Please check with the latest and reopen this github issue if you still encounter the mentioned error.
