### ISSUE TITLE
Record inclusion is not properly rendered in VSCode multi service view

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/ballerina-plugin-vscode#243]
**Description:**

Consider a record set as follows. 

<img width="586" alt="image" src="https://user-images.githubusercontent.com/16300038/199310824-2b946deb-14d8-48bb-866f-2e3ec9db3b02.png">

The generated diagram is having an arrow which is not properly placed.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/16300038/199311035-030e4f52-88a8-4768-80d2-3c90c7fed6ab.png">

**Comment by SumayyaZiyad** [comment]
Right now, this is expected behaviour because of the dedicated ports used for inclusions. So, a straight directed arrow is generated from the **top** port of the type to the **bottom** port of the included type (regardless of the positioning). The outlook in the above picture is due to the arrangement of the nodes.

As an improvement, we can check the possibility of making sure that for inclusions the related entities are always vertical in order, regardless of the other connections.

**Comment by anupama-pathirage** [comment]
Understood. But can we make a small difference to the arrow pointer? 

Since the triangle is an equilateral triangle (it seems), it looks like the arrow is pointing to the canvas instead of the `StudentProfile` box. 
So either making the. pointer bit different or add a curved line to show the pointer is pointing upwards will solve the issue. If we move the `StudentProfile` box towards up, it solves the issue. But the default diagram looks like it points to free space in the canvas.

<img width="209" alt="image" src="https://user-images.githubusercontent.com/16300038/199542750-300b329e-7e85-42e1-b4cc-deff836b9522.png">

**Comment by SumayyaZiyad** [comment]
+1. Will make the improvements.
