### ISSUE TITLE
Data mapper - Array with complex records wont open in the data mapper

### ISSUE THREAD

**Issue by dhanushkasandakelum117** [wso2/ballerina-plugin-vscode#382]
I was doing a data transformation between HL7v23 and FHIR and the data records in HL7v23 which has complex records as arrays wont show its fields in data mapper. Therefore i couldn't do the correct data mapping.

For instance in the input record pid5 is a array with complex record. So if it is expanded then i could easily do the mapping to the respective field of the output record. But since it is not expanded or wont opened in the data mapper that cant be done.

Check out the discord link {Images are there}
https://discordapp.com/channels/957996897782616114/1062816978349342830/1062816978349342830

Check out my repo: https://github.com/DhanushkaSandakelum/Ballerina/tree/main/data_mapper-hl7v23_fhir_mapping

**Comment by madushajg** [comment]
Actually the data mapper does not expand and display the fields of arrays resides within inputs since the number of fields within the array is unknown as the arrays are dynamic in most of the time. You can go with member access expression, query expressions or array functions to achieve the requirement.
