### ISSUE TITLE
[Record Editor] Failed to create separate record definitions from a give JSON

### ISSUE THREAD

**Issue by madushajg** [wso2/ballerina-plugin-vscode#408]
**Description:**
$Subject
![record-editor-seperate-records](https://user-images.githubusercontent.com/26219651/216887008-8c116715-84a0-4f86-8d6d-cc260cecff32.gif)

sample JSON:
```json
{
	"id": "0001",
	"name": "Cake",
	"score": 0.55,
	"status": {
		"kind": "D"
	}
}
```

**Affected Versions:**
Ballerina 2201.3.2
Plugin 3.3.8

**Comment by tharindulak** [comment]
As per the discussion with @AzeemMuzammil @kaviththiranga the logic for the name generation has changed. The issue here is that the name given via the UI is sent to the LS to get the generated code with respective records. There in the BE the first letter is capitalised which the FE is unaware. As a fix we thought of capitalising the first letter of the user input when he is typing the name (according to the ballerina conventions). So the name mismatch would not happen since users are giving a record name with capitalised first letter.
